//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType = true)]
[XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class result
{

    private resultMenus[] menusField;
    private string requestField;
    private string request_timestampField;

    /// <remarks/>
    [XmlElementAttribute("menus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultMenus[] menus
    {
        get { return this.menusField; }
        set { this.menusField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string request
    {
        get { return this.requestField; }
        set { this.requestField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string request_timestamp
    {
        get { return this.request_timestampField; }
        set { this.request_timestampField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType = true)]
public partial class resultMenus
{

    private resultMenusMenu[] menuField;
    private string zoneField;
    private string typeField;

    /// <remarks/>
    [XmlElementAttribute("menu", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultMenusMenu[] menu
    {
        get { return this.menuField; }
        set { this.menuField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string zone
    {
        get { return this.zoneField; }
        set { this.zoneField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType = true)]
public partial class resultMenusMenu
{

    private resultMenusMenuItemsItem[] itemsField;
    private string canteenField;
    private string mealField;
    private string dateField;
    private string weekdayField;
    private string weekdayNrField;
    private string disabledField;

    /// <remarks/>
    [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("item", typeof(resultMenusMenuItemsItem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultMenusMenuItemsItem[] items
    {
        get { return this.itemsField; }
        set { this.itemsField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string canteen
    {
        get { return this.canteenField; }
        set { this.canteenField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string meal
    {
        get { return this.mealField; }
        set { this.mealField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string date
    {
        get { return this.dateField; }
        set { this.dateField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string weekday
    {
        get { return this.weekdayField; }
        set { this.weekdayField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string weekdayNr
    {
        get { return this.weekdayNrField; }
        set { this.weekdayNrField = value; }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string disabled
    {
        get { return this.disabledField; }
        set { this.disabledField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType = true)]
public partial class resultMenusMenuItemsItem
{

    private string nameField;
    private string valueField;

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name
    {
        get { return this.nameField; }
        set { this.nameField = value; }
    }

    /// <remarks/>
    [XmlTextAttribute()]
    public string Value
    {
        get { return this.valueField; }
        set { this.valueField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType = true)]
[XmlRootAttribute("result", Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private result[] itemsField;

    /// <remarks/>
    [XmlElementAttribute("result")]
    public result[] Items
    {
        get { return this.itemsField; }
        set { this.itemsField = value; }
    }
}
